---
title: "R数据挖掘简介"
author: "黄勇"
date: "2016年3月7日"
fontsize: 14pt
output: 
  slidy_presentation: 
    incremental: yes
    font_adjustment: 4
    keep_md: yes
---

## 基本配置和安装包

在windows的系统上安装官方R语言解释器或者推荐微软[RRO](http://www.revolutionanalytics.com/revolution-r-open)、集成开发环境[RStudio](https://www.rstudio.com/home/)


- 安装doParallel/foreach/openBLAS等包加速矩阵运算

- 安装devtools从Github上安装拓展包

```{r}
#使用?和help()函数查看帮助
#install.packages("ggplot2")
library(ggplot2)
#detach(ggplot2)
#search();getwd()
#a=matrix(rnorm(1),40,40)
#b=t(a)
#c=a%*%b
```

## R基本数据类型和操作

- R和MATLAB类似，所有的数据类型都是向量
- 常见的数据类型有charactor、numeric、factor、list、matrix、dataframe
- 可以参考《R语言实战》、《学习R》等书。

```{r}
#demo(graphics)
#rm(list=ls())
x<-rnorm(100,sd=1,mean=1)
t.test(x);matrix(1:6,nrow = 2)

```

## 使用内置数据集探索数据

- 使用ggplot2包进行数据预处理和数据可视化展示

```{r}
# summary(cars);view(cars);head(cars,3)
library(ggplot2)
qplot(cars$speed,cars$dist,xlab="速度",ylab="距离",colour='r')
```

## 使用dplyr和tidyr操纵数据

- 对数据进行查找、清洗和转换

```{r, eval=FALSE}
#按照平均值统计iris
library(dplyr);dplyr::summarise_each(iris,funs(mean))
#过滤出花萼长度大于7的数据
#dplyr::filter(iris,Sepal.Length>7)
#重复采样
#dplyr::sample_n(iris,50,replace = TRUE)

#select、join筛选数据,类似SQL查询
a=dplyr::select(iris,Sepal.Length,Sepal.Width);head(a)
```

## 一个简单的线性回归的例子

```{r}
ind=sample(nrow(cars),nrow(cars)/2);train=cars[ind,];test=cars[-ind,]
lm.model=lm(train$dist~train$speed);summary(lm.model);new=data.frame(test$speed)
y1=predict(lm.model,new)
cor(y1,test$dist)
```


